[package]
name = "sleigh_derive"
version = "0.1.0"
authors = ["Erik Gilling <konkers@konkers.net>"]
edition = "2018"

[lib]
proc-macro = true

[dependencies]
syn = { version = "0.14.4", features = ["derive", "parsing", "printing", "clone-impls", "proc-macro", "extra-traits"] }
quote = "0.6.3"